# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Sphinx settings
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: true

# Python settings
python:
   version: 3.7
   install:
      - method: pip
        path: .
        extra_requirements:
            - docs
